dist: xenial
language: python
python: '3.7'

env:
  global:
    - COLLECTION_NAMESPACE: lvrfrc87
    - COLLECTION_NAME: git_acp
  matrix:
  - ANSIBLE_VERSION=latest
branches:
  only:
  - master
  - dev

install:
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
- pip install ansible-lint
before_script:
  # - cd ../
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
script:
- ansible-test sanity --docker -v plugins/modules/
# - ansible-lint tests/integration/targets/git_acp/tasks/main.yml
- ansible-test integration -v --docker
