dist: xenial
language: python
python: '3.7'

env:
  global:
    - COLLECTION_NAMESPACE: lvrfrc87
    - COLLECTION_NAME: git_acp
  matrix:
  - ANSIBLE_VERSION=latest

install:
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
- pip install ansible-lint
before_script:
  # - cd ../
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

deploy:
  - povider: script
    script: deployment/dev.sh
    on:
      branch: dev
  - povider: script
    script: deployment/master.sh
    on:
      branch: master