dist: xenial
language: python
python: '3.7'

env:
  global:
    - COLLECTION_NAMESPACE: lvrfrc87
    - COLLECTION_NAME: git_acp
  matrix:
    - ANSIBLE_VERSION=latest
install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install
    ansible==$ANSIBLE_VERSION; fi
  - pip install ansible-lint
before_script:
  # - cd ../
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

jobs:
  include:
  - stage: dev
    if: branch = dev
    script: ./deployment/dev.sh
  - stage: master
    if: branch = master
    script: ./deployment/master.sh

